const mongoose = require('mongoose');

const Project = mongoose.Schema({

    // Name: { type: String, required: true },
    // Projecttime1: { type: String,  required: true },
    // Projecttime2: { type: String,  required: false },
    // Projecttime3: { type: String,  required: false },
    // TrainingLearningtime:{ type: String,  required: false },
    // Project1:{ type: String,  required: true },
    // Project2:{ type: String,  required: false },
    // Project3:{ type: String,  required: false },
    // TrainingLearing:{ type: String,  required: false },
    // Date:{ type: String,  required: true },
    // TotalTime:{ type: String,  required: true },


    Name: { type: String, required: true },
    Projecttimefrom1: { type: String, required: true },
    Projecttimeto1: { type: String, required: true },
    // Name: { type: String, required: false },
    // Projecttimefrom1: { type: String, required: false },
    // Projecttimeto1: { type: String, required: false },
    Projecttimefrom2: { type: String, required: false },
    Projecttimeto2: { type: String, required: false },
    Projecttimefrom3: { type: String, required: false },
    Projecttimeto3: { type: String, required: false},
    Projecttimefrom4: { type: String, required: false },
    Projecttimeto4: { type: String, required: false},
    Projecttimefrom5: { type: String, required: false },
    Projecttimeto5: { type: String, required: false },
    TrainingLearing: { type: String, required: false },
    TrainingLearningtimefrom: { type: String, required: false},
    TrainingLearningtimeto: { type: String, required: false },
    Project1: { type: String, required: true },
    // Project1: { type: String, required: false },
    Project2: { type: String, required: false },
    Project3: { type: String, required: false },
    Project4: { type: String, required: false },
    Project5: { type: String, required: false },
    activity1: { type: String, required: false },
    activity2: { type: String, required: false},
    activity3: { type: String, required: false},
    activity4: { type: String, required: false },
    activity5: { type: String, required: false},
    activity6: { type: String, required: false },
    TodayDate: { type: String, required: true },
    // TodayDate: { type: String, required: false},
    totaltimeproject1: { type: String, required: true },
    // totaltimeproject1: { type: String, required: false },
    totaltimeproject2: { type: String, required: false },
    totaltimeproject3: { type: String, required: false },
    totaltimeproject4: { type: String, required: false },
    totaltimeproject5: { type: String, required: false },
    totalTrainingLearning: { type: String, required: false },
    totaytotaltime:{ type: String, required: true },

});

module.exports = mongoose.model('UserProject',Project);